language: php

php:
    - 7.1
    - 7.2

before_script:
    - composer install --dev --prefer-source --no-interaction
    - cp .env.travis .env
    - php artisan key:generate

script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpcs app tests --standard=PSR2
