version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: build/Dockerfile
        ports:
            - 1215:1215
    redis:
        image: redis
        ports:
            - 6379:6379
