version: '3'

services:
    app:
        build:
            context: .
            dockerfile: build/Dockerfile
        ports:
            - "80:80"
        depends_on:
            - redis
    redis:
        image: redis
