debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
